### ISSUE TITLE
Compatible Parity Signer App versions

### ISSUE THREAD

**Issue by DrW3RK** [paritytech/parity-signer-companion#100]
I tested Parity Signer App 5.0.0 on iOS with Parity Signer Companion and it seemed to work seamlessly.

I then switched to Parity Signer App 4.5.3 and was able to import the account to the companion. But the QR scanner on the app is failing to recognize the QR codes presented in the popup windows of Parity Signer Companion app. Is this an isolated issue with my specific phone or it is an issue with the app's version on my Andriod phone?

**Comment by Slesarew** [comment]
This is most probably a known (to me at least) hardware bug in some versions of android QR recognition system. Please try right-clicking on the QR and opening it in a viewer with white background, it should work seamlessly - of course that's a temporary solution (do let me know if it does not work!).

I recommend switching to 5.+ version of Signer now, of course. Remember that you can't upgrade, only wipe the old app and install a new one, preferably after phone factory reset.

**Comment by AndreiEres** [comment]
@DrW3RK I updated firefox extension: https://addons.mozilla.org/en-US/firefox/addon/parity-signer-companion/

Could you check this bug with new version?

**Comment by Slesarew** [comment]
Fixed on my test devices

**Comment by DrW3RK** [comment]
Tested with the new version. My Android phone recognizes the QR codes now. Receiving a different error regarding Metadata/chainspec, but that is not relevant for this. Closing!
