### ISSUE TITLE
Removing keys from extension

### ISSUE THREAD

**Issue by wirednkod** [paritytech/parity-signer-companion#94]
When trying to remove a key from extension a countdown begins (10 seconds).
If the user closes the popup window of the extension (apparently) the countdown stops and the account is never removed. 

If that is the correct functionality, I think there should be a note saying: "Do not close popup until key is removed"

**Comment by wirednkod** [comment]
Moved to [parity-signer repo](https://github.com/paritytech/parity-signer/issues/880)

**Comment by AndreiEres** [comment]
That extra interface was removed in https://github.com/paritytech/parity-signer-companion/pull/121.
